/*
 * ADC_test_interface.c
 *
 * Created: 9/19/2023 4:42:22 PM
 *  Author: youssef
 */ 

#include "MATH.h"
#include "STD_TYPE.h"
#include "ADC_test_private.h"
#include "ADC_test_interface.h"

void ADC_Vid_Init(){
	
	/* THE FIRST THREE BITS IN (ADCSRA_REG) RESPONSIBLE FOR PRESCALAR SELECTION */
	ADCSRA_REG &= 0b11111000;
	ADCSRA_REG |= ADC_PRESCALER;
	/* BIT(7,6) IN (ADMUX_REG) RESPONSIBLE FOR Voltage Reference Selections for ADC ACCORDING TO THE TABLE ---> AVCC with external capacitor at AREF pin */
	CLR_BIT(ADMUX_REG,7);
	SET_BIT(ADMUX_REG,6);
	/* BIT 7 IN (ADCSRA_REG) RESPONSIBLE FOR ENABLE ADC */
	SET_BIT(ADCSRA_REG,7);
}

u16 ADC_u16_ReadChannel(u8 copy_u8_channel){
	
	/*THE FIRST 5 BITS IN (ADMUX_REG) REPONSIBLE FOR INPUT CHANNEL AND GAIN SELECTION ACCORDING TO THE TABLE */
	ADMUX_REG &= 0b11100000 ;
	ADMUX_REG |= copy_u8_channel ;
	/* BIT 6 IN (ADCSRA_REG) RESPONSIBLE FOR STARTING THE CONVERSION PROCESS (DIGITAL -> ANALOG) */
	SET_BIT(ADCSRA_REG,6) ;
	/* BIT 4 IN (ADCSRA_REG) "ADIF -> ADC INTERRUPT FLAG" IS SET TO 1 AUTOMATICALLY WHEN THE ADC CONVERSION COMPLETED THEN YOU MUST CLEAR IT TO MAKE A NEW ADC CONVERSION (ADIF is cleared by writing a logical one to the flag) */
	while(GET_BIT(ADCSRA_REG,4)==0) ; // BUSY WAIT WHILE THE ADC CONVERSION NOT COMPLETED
	SET_BIT(ADCSRA_REG,4) ;           // CLEAR IT TO MAKE A NEW CONVERSION AGAIN
	/* THE VALUE OF THE CONVERSION IS SETTED AUTOMATICALLY TO (ADCH AND ADCL) ---> RETURN ADC_REG (ADCH + ADCL) */
	return ADC_REG  ;
}
