/*
 * EXT_private.h
 *
 * Created: 9/11/2023 4:21:28 PM
 *  Author: youssef
 */ 


#ifndef EXT_PRIVATE_H_
#define EXT_PRIVATE_H_




/* MCUCR_REG RESPONSIBLE FOR ACTIVATING THE SPECIFIC STAGE OF INTERRUPT (INT1, INT0) (LOW LEVEL, ANY CHANGE, FALLING EDGE, RISING EDGE) */
#define MCUCR_REG      *((volatile u8*)0x55)
/* INTERRUPT SENSE CONTROL (BITS OF MCUCR_REG) BY WHICH YOU CAN CHOOSE THE ACTIVATED SPECIFIC STAGE */
#define  ISC11    3
#define  ISC10    2
#define  ISC01    1
#define  ISC00    0


/* MCUCSR_REG RESPONSIBLE FOR ACTIVATING THE SPECIFIC STAGE OF INTERRUPT (INT2) (FALLING EDGE, RISING EDGE) */
#define MCUCSR_REG      *((volatile u8*)0x54)
/* INTERRUPT SENSE CONTROL (BITS OF MCUCSR_REG) BY WHICH YOU CAN CHOOSE THE ACTIVATED SPECIFIC STAGE */
#define  ISC2    6


/* GICR_REG RESPONSIBLE FOR ENABLING THE EXT INTERRUPT (INTO, INT1, INT2) (WITH SREG_REG) */
#define GICR_REG      *((volatile u8*)0x5B)
/* BITS OF GICR_REG BY WHICH YOU CAN ENABLE THE EXT INTERRUPT (INT1, INT0, INT2) */
#define  INT_1    7
#define  INT_0    6
#define  INT_2    5




#endif /* EXT_PRIVATE_H_ */